print("hello,world!")
print("hello again!")
#print("i like typing this")
print("this is fun")
print("this is python class \\n in tarzanskills")
print("i like typing this.")
print("hello this is harsha \\t my qualification is \n mca")
print("root", "node", "child",sep='->')
print("this","is","python","class" ,sep='->')
print("hello",end='')
print("world")
